#!/usr/bin/env bash

# Parse options
while getopts ":m:a:" opt; do
  case $opt in
    m | a)
        declare "option_${opt}=${OPTARG:-0}"
      ;;
    \?)
      echo >&2 "Please provide valid flags."
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

# Get authors list
IFS=',' read -a authors <<< "${option_a}"

# Iterates over each author and prepend Co-authored-by text
for author_index in "${!authors[@]}"
do
	authors[$author_index]="Co-authored-by: ${authors[author_index]}"
done

# Make commit message
commit_message=$(printf "%s\n\n\n%s\n" "Fix typo and refactor code" "${authors[@]}")

# Run command
git_output=`git commit -m "$commit_message"`

echo "$git_output"
