#!/usr/bin/env bash

# Get options
while getopts ":m:a:" opt; do
  case $opt in
    m | a)
        declare "option_${opt}=${OPTARG:-0}"
      ;;
    \?)
      echo >&2 "Please provide valid flags."
      exit 1
      ;;
  esac
done

shift $((OPTIND-1))

# get authors
IFS=',' read -a authors <<< "${option_a}"

# add Co-authored-by at start of each author
for author_index in "${!authors[@]}"
do
	authors[$author_index]="Co-authored-by: ${authors[author_index]}"
done

# make commit message
commit_message=$(printf "%s\n\n\n%s\n" "Fix typo and refactor code" "${authors[@]}")

git_output=`git commit -m "$commit_message"`

echo "$git_output"
